apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
spec:
  destination:
    namespace: sample-app-secret
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sample-app-secret/
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/PathogenDE/argocd-exp
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true