apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: sample-app-secret    
spec:
  containers:
  - name: nginx
    env:
      - name: super_secret
        value: <path:argocd/sample#super_secret>
    image: nginx:1.14.2
    ports:
    - containerPort: 80
